### ISSUE TITLE
[Model] Fetch views from CC backend

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#124]
When fetching metadata from CC backend, e.g., we call `package_show` API action, it doesn't include information about the views. As a result, frontend doesn't know about pre-defined view objects and developers cannot implement renderers for it. Therefore, we need to fetch views together with package/resource metadata from CKAN Classic backend in the model layer.

## Acceptance criteria

* [x] dataset metadata includes all resource views from CKAN Classic backend

## Tasks

* [x] Analysis
* [x] Implement a new method for fetching resource views
* [x] `getPackage` should fetch views for each resource
* [x] update the mocks so everything works ok
* [x] converter `CKAN view` => `Data Package view` 

## Analysis

DMS model: https://github.com/datopian/frontend-v2/blob/master/lib/dms.js

Method for fetching metadata from CC: https://github.com/datopian/frontend-v2/blob/master/lib/dms.js#L34

CKAN descriptor => Data Package: https://github.com/datopian/frontend-v2/blob/master/utils/index.js#L5

Currently, we're calling `package_show` API to get information about package and its resources. Since the response doesn't contain metadata about resource views, we need to make additional calls to fetch views metadata for each resource:

* method: GET
* action: `resource_view_list`
* params: `id` (resource id)

### CKAN View => Data Package View

Known CKAN view types:

At the moment, we're considering the following examples of CKAN view (might be more types, e.g., custom types etc.):

  1. recline_view => Data Explorer with Table view, Chart Builder, Map Builder
    and Query Builder.
  2. geojson_view => Leaflet map
  3. pdf_view => our PDF viewer
  4. recline_grid_view => our Table viewer
  5. recline_graph_view => our Simple graph
  6. recline_map_view => our Leaflet map
  7. image_view => not supported at the moment
  8. text_view => not supported at the moment
  9. webpage_view => not supported at the moment

Dictionary of CKAN view type => Data Package Spec Type:

```
{
    recline_view: 'dataExplorer',
    geojson_view: 'map',
    pdf_view: 'document',
    recline_grid_view: 'table',
    recline_graph_view: 'simple',
    recline_map_view: 'map'
}
```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/frontend-v2/commit/8d8a504f63c1f32daa995d3a079362755065e331 and https://github.com/datopian/frontend-v2/commit/2356c9976b8c7ee65b822b30ab1b34957d21cbd1
