### ISSUE TITLE
Resource view display in dataset show page are model driven and "clean"

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#126]
Refactor dataset view controller to remove auto-view generation and to clean up in general (e.g. where stuff is generated) ...

## Acceptance criteria

* [ ] The resource views for a resource are displayed
* [ ] When there are no views a resource block is not shown (??) (because you can already download that resource from the resources summary table)
  * [ ] and the resources summary table disables the link for "more info / preview"
* [ ] When there are multiple views they are display one beneath each other ... (TODO: or with a switcher??)
* [ ] Support dataset level views
* [ ] There is simple documentation or an example of how to customize this per site
  * [ ] I can change the simple html and layout of a resource block without having to alter the controller i.e. just by editing a template ...

## Tasks

* [ ] Are there any sites that will break and where we need to enable that ?? Ans: No ... 
* [ ] Add a test or two for this page and esp for resource display section (try and do something not too tied to the exact html)
* [ ] Remove auto-generation (tests should still pass assuming mock data has resource views OR may need to update tests a bit)
* [ ] Refactoring the views html stuff (maybe in templlate first )
* [ ] Refactoring where the resource display stuff gets generated ...

### What does the dataviews.js stuff need?

There are 2 libraries

* data-explorer.js
* data-package-views.js

Data Explorer

```htmlmixed=
<div class="data-explorer" id="..." data-datapackage="{...}" ></div>

<!-- where datapackage is -->
<srcipt>
  const datapackage = {
    resources: [{resource}], // single resource for this view
    views: [...], // can be 3 views aka widgets
    controls: { 
      showChartBuilder: true,
      showMapBuilder: true 
    }
  }
</srcipt>

<!-- import data explorer -->
<srcipt src=""></srcipt>
```

Data View Example

### Resource display

"Big"

```htmlmixed=
<h2 id="{resource-name}">Resource Title</h2>

Datastore API link 

Resource description

{Views}
<!-- view 1  ... -->
<div ... datapackage=""></div>
```

"Small"

```htmlmixed=
{Views}
<div ... datapackage=""></div>
```

Main template

{% for resourceDisplay in resourceDisplay %}

html using the resourceDisplay object ... 

Then later ... just the html and you generate the html in the controlller

nunjucks.render(resourceDisplaySnippt, resourceObj)

{{ resourceDisplay }}
