### ISSUE TITLE
[CMS][WP] Ability to view draft pages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#161]
When I'm preparing pages in the WordPress, I want to view draft pages in my staging/test site, so that I can make sure it looks great prior to publishing it in production.

## Acceptance criteria

* [ ] I can quickly configure my staging/test site to display draft pages

## Tasks

* [ ] Update docs at http://tech.datopian.com/frontend/plugins/#wp
  * [ ] It should explain how to use `WP_SHOW_DRAFT`
* [ ] Use `WP_SHOW_DRAFT` env var as an option when hitting WP API
  * see status param in https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/

## Analysis

Set up `baseQuery` in CMS model constructor so that it's used by all methods:

https://github.com/datopian/frontend-v2/blob/master/plugins/wp/cms.js#L9-L11

```javascript
constructor() {
  this.blog = wpcom.site(config.get('WP_URL'))
  this.baseQuery = {
    status: 'publish' + config.get('WP_SHOW_DRAFT') ? ',draft' : ''
  }
}
```

Then it should be used by all methods:

```javascript
async getListOfPostsWithMeta(query) {
  return await this.blog.postsList(Object.assign(this.baseQuery, query))
}
```

**Comment by sagargg** [comment]
Already implemented. 
https://github.com/datopian/frontend-v2/blob/master/plugins/wp/cms.js#L9-L14
