### ISSUE TITLE
CI/CD: move from Travis to Github Actions

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#196]
Since Travis-ci.org is now not working, we want to use this opportunity to move to GH Actions that is default in our projects.

## Acceptance criteria

* [x] The tests are running in the CI using GH Actions

## Tasks

* [x] Remove Travis config
* [x] Add GH Actions config (using node v12)
* [x] Run tests in the CI

**Comment by anuveyatsu** [comment]
FIXED in #198
