### ISSUE TITLE
[EPIC] Plugin / Extensibility for CKAN NG frontend

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#22]
As a Developer i want to add functionality (new pages/routes and new middleware) to an existing frontend without having to fork the frontend so that I can make a richer data portal and work quickly without breaking the core and without having to make product decisions.

## Acceptance Criteria

- [x] Developer can extend frontend with plugin that adds custom middleware
- [x] Developer can implement routes from plugin that implement custom controller logic and template

## Tasks

- [x] Create NPM @ckan namespace for ckan modules  https://github.com/datopian/frontend-v2/issues/23 [2hrs]
- [x] Add environment variables and logic required to load extensions from local environment or from NPM https://github.com/datopian/frontend-v2/issues/24 [8hrs]
- [x] Add developer docs of extensibility https://github.com/datopian/frontend-v2/issues/27 [4hrs]

**Comment by anuveyatsu** [comment]
@starsinmypockets do you think we can close it now?

**Comment by anuveyatsu** [comment]
Closing this epic as FIXED. See docs about plugin / extensibility here - http://tech.datopian.com/frontend/#theming-2 and http://tech.datopian.com/frontend/#extending-plugins-2
