### ISSUE TITLE
Create NPM @ckan namespace for ckan modules

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#23]
## Description
As an X I want to be able to find and publish NPM modules under the `@ckan` namespace to help facilitate faster frontend development

## Acceptance criteria
- [ ] Publish library to @ckan namespace (example - publish @ckanext-datapackage-views-js)

## Tasks
- [ ] Setup namespace with npm [1hr]
- [ ] Publish package to namespace [1hr]

**Comment by anuveyatsu** [comment]
@starsinmypockets do you mean scopes? E.g., you want to have an org and publish packages under that - `@ckan/datapackage-views-js`? But I don't think datapackage-views-js is a good example.

**Comment by starsinmypockets** [comment]
Yes.

**Comment by anuveyatsu** [comment]
@starsinmypockets we are already using `@datopian` scope on NPM:

https://www.npmjs.com/settings/datopian/packages

So closing this issue as FIXED.
