### ISSUE TITLE
Add developer docs for frontend extension patterns [4hrs]

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#27]
## Description
Add documentation of how to extend frontend

## Tasks
- [ ] High level 
- [ ] Adding custom plugins
- [ ] Adding extensions via npm
- [ ] Adding custom routes via themes
- [ ] Adding custom middleware via themes

**Comment by anuveyatsu** [comment]
We have done in details docs for the frontend app here - http://tech.datopian.com/frontend/

High level - http://tech.datopian.com/frontend/#design-how-it-works

Theming - http://tech.datopian.com/frontend/#theming-2

Extending - http://tech.datopian.com/frontend/#extending-plugins-2
