### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#32]
As a site owner, I want to know how many users are visiting my site and how they are interacting with the site so that I can get insights into the use and develop the site accordingly.

## Acceptance criteria

* [x] I have everything in the list above working

## Tasks

* [x] Analysis, eg, we can implement it in frontend-v2 master so that you just add `GA_ID` or similar env var to make it work
* [x] Add GA script in the `base.html`
* [x] Make the GA ID configurable via env var

**Comment by anuveyatsu** [comment]
@svetozarstojkovic can you please update this issue? Generally, can you tick items as soon as they're done so we can understand where we are at?

**Comment by svetozarstojkovic** [comment]
For this to work, you need to make one additional adjustment.
Add "GA_ID=UA-XXXXXXXXX-Y" (Google Analytics tracker id) to your .env file.

**Comment by svetozarstojkovic** [comment]
Google analytics has been implemented as a plugin, info how to use it can be found in README of the repo.
Since PR has been merged, this ticket can be closed.
